language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

script:
  - go build -v ./benchmark/client
  - go build -v ./benchmark/server
  - go build -v ./helloworld/client
  - go build -v ./helloworld/server
